# Generated by Django 5.0.6 on 2024-06-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_user_alter_skill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
