# Generated by Django 5.0.6 on 2024-06-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_website_project_discord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='website',
            new_name='discord',
        ),
        migrations.RemoveField(
            model_name='project',
            name='discord',
        ),
    ]
