# Generated by Django 5.0.6 on 2024-06-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_website_userprofile_discord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
